README.md

Add new link for Writing clean code pdf

---

src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java

- Implemented AuthenticationManager
- Commented code to avoid dependency loop
* ...
* ....

OT231-33: Validate role

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/ContactEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IContactRepository.java

- Created Contact Entity
- Created Contact Repository
* ...
* ....

OT231-53: Crear modelo y repositorio de Contactos

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/ActivityEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IActivityRepository.java

- Created Activity entity
- Created Activity repository
* ...
* ....

OT231-21: Create model and repository Activity

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/RoleEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IRoleRepository.java

OT231-16 Create Model and repository role

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IUserRepository.java

- Created User Entity
- Created User Repository
* ...
* ...
* ....

OT231-17: add user entity and repository

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/MemberEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IMemberRepository.java

- Created Member entity
- Created Member Repository
* ...
* ...
* ....

OT231-22: add Member entity and repository

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/TestimonialEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ITestimonialRepository.java

- Created Testimonial Entity
- Created Testimonial Repository
* ...
* ...
* ....

OT231-20: add Testimonial entity and repository

---

src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java

- Add Request Filter in Security Config Class
* ...
* ....

OT231-73: Protect admin routes by jwt

---

pom.xml
src/main/java/com/alkemy/ong/application/exception/ThirdPartyException.java
src/main/java/com/alkemy/ong/application/util/IEmail.java
src/main/java/com/alkemy/ong/application/util/ISendEmail.java
src/main/java/com/alkemy/ong/application/util/SendEmailDelegate.java
src/main/java/com/alkemy/ong/infrastructure/config/sendgrid/SendgridConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/exception/DefaultExceptionHandler.java
src/main/java/com/alkemy/ong/infrastructure/util/SendEmailDelegate.java
src/main/resources/application.properties
src/main/resources/application.yaml
src/test/resources/application.yaml

- Created Email interface
- Created SendEmail interface
- Add Sendgrid dependency to pom.xml
- Created application.properties
- Created SendEmailDelegate service
- Created ThirdPartyException class
* ...
* ....

OT231-27: Integrate email sending

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/CommentEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ICommentSpringRepository.java

- Se agrega la posibilidad de agregar Comentarios a una Novedad.
- Contempla las relaciones correspondientes con User y News entities.
* ...
* ...
* ....

OT231-74: add Comment Entity and Repository

---

src/main/java/com/alkemy/ong/application/repository/ICategoryRepository.java
src/main/java/com/alkemy/ong/application/service/CategoryService.java
src/main/java/com/alkemy/ong/application/service/usecase/ICreateCategoryUseCase.java
src/main/java/com/alkemy/ong/domain/Category.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/CategoryEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/CategoryRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CategoryMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/CategoryRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/CategoryResourse.java
src/main/java/com/alkemy/ong/infrastructure/rest/response/CategoryResponse.java

OT231-42 : Category creation Endpoint

---

src/main/java/com/alkemy/ong/infrastructure/config/seeder/SeedActivities.java

OT231-52 : Create Activity Seeder

---

src/main/java/com/alkemy/ong/infrastructure/rest/request/ContactRequest.java

[Bug fixing] modify regexp pattern in ContactRequest

---

src/main/java/com/alkemy/ong/application/repository/ICategoryRepository.java
src/main/java/com/alkemy/ong/application/service/CategoryService.java
src/main/java/com/alkemy/ong/application/service/usecase/IListCategoryUseCase.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/CategoryEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/CategoryRepository.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/spring/ICategorySpringRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CategoryMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/CategoryResource.java
src/main/java/com/alkemy/ong/infrastructure/rest/response/ListCategoryResponse.java
src/main/resources/application.yaml

OT231-40 Endpoint Listado de Categorías

---

src/main/java/com/alkemy/ong/application/service/UserService.java
src/main/java/com/alkemy/ong/application/util/template/ContactEmailTemplate.java
src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/test/java/com/alkemy/ong/application/service/UserServiceTest.java

- Add Contact Email Template
- Update WelcomeEmailTemplate
- UserServiceTest and ServiceBeanConfig
- Add sendWelcomeMail method to User Service class
* ...
* ....

OT231-30:  Sending Welcome Email

---

src/main/java/com/alkemy/ong/application/repository/IUserRepository.java
src/main/java/com/alkemy/ong/application/service/UserService.java
src/main/java/com/alkemy/ong/application/service/usecase/IUpdateUserUseCase.java
src/main/java/com/alkemy/ong/domain/Role.java
src/main/java/com/alkemy/ong/domain/User.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/RoleEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/UserEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/UserRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/UserMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/UpdateUserRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/UserRegisterRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/UserResource.java
src/test/java/com/alkemy/ong/application/service/UserServiceTest.java
src/test/java/com/alkemy/ong/bigtest/user/UpdateUserIntegrationTest.java

- Created endpoint to update users
- Created UpdateUserRequest dto
- Created IUserUpdateUseCase
- Updated User Service
- Updated User Repository
- Updated SecurityConfig.class
- Added new Integration Test
- Created a Role domain object that is used as an attribute in User domain
- Created a RoleEntityMapper for setting Roles when updating User Entity
* ...
* ...
* ....

OT231-34: update User endpoint

---

src/main/java/com/alkemy/ong/application/repository/IActivityRepository.java
src/main/java/com/alkemy/ong/application/service/ActivityService.java
src/main/java/com/alkemy/ong/application/service/usecase/ICreateActivityUseCase.java
src/main/java/com/alkemy/ong/domain/Activity.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/ActivityEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ActivityRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/ActivityRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/ActivityResource.java
src/main/java/com/alkemy/ong/infrastructure/rest/response/ActivityResponse.java

- Endpoint create activity add
* ...
* ...
* ....

OT231-50: Endpoint Creación Actividades add

---

src/main/java/com/alkemy/ong/application/repository/ITestimonialRepository.java
src/main/java/com/alkemy/ong/application/service/TestimonialService.java
src/main/java/com/alkemy/ong/application/service/usecase/ICreateTestimonialUseCase.java
src/main/java/com/alkemy/ong/domain/Testimonial.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/TestimonialsEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/TestimonialRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/TestimonialMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/TestimonialRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/TestimonialResource.java
src/main/java/com/alkemy/ong/infrastructure/rest/response/TestimonialResponse.java

OT231-65 Create Testimonial Endpoint

---

src/test/java/com/alkemy/ong/bigtest/BigTest.java
src/test/java/com/alkemy/ong/bigtest/contact/GetListContactsIntegrationTest.java

- integration test list contacts
* shouldReturn403WhenAuthTokenIsNotValid()
* shouldReturnListContactsAndStatus200WhenRequestHasValidToken()
* shouldReturnEmptyContactListAndStatus200WhenNoRecordsExist()
* shouldReturnEmptyContactListAndStatus200WhenContacsIsNotActive()
* ![image](https://user-images.githubusercontent.com/27240930/179096180-6803484e-4036-42d2-947a-ecdedf0f198c.png)

PR: OT231-95: Test Integration List Contact

---

etc/postman/OT231.postman_collection.json
src/main/java/com/alkemy/ong/application/repository/ICommentRepository.java
src/main/java/com/alkemy/ong/application/service/CommentService.java
src/main/java/com/alkemy/ong/application/service/usecase/IUpdateCommentUseCase.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/CommentRepository.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/spring/ICommentSpringRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CommentMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/UpdateCommentRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/CommentResource.java
src/test/java/com/alkemy/ong/bigtest/BigTest.java
src/test/java/com/alkemy/ong/bigtest/comment/DeleteCommentIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/comment/UpdateCommentIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/contact/GetListContactsIntegrationTest.java

- Update ICommentRepository and Created IUpdateCommentUseCase 
- Update ServiceBeanConfig and SecurityConfig classes 
- Update CommmentRepository and ICommentSpringRepository 
- Update Comment Mapper and Comment Entity Mapper 
- Update Comment Service 
- Created UpdateCommentRequest and Update Comment Resource 
- Update Postman Collection 
- Update Big test 
- Created UpdateCommentIntegrationTest 
- Created DeleteCommentIntegrationTest 
**Test …

OT231-77: Endpoint Update Comments

---

pom.xml
src/main/java/com/alkemy/ong/application/repository/IMemberRepository.java
src/main/java/com/alkemy/ong/application/service/MemberService.java
src/main/java/com/alkemy/ong/application/service/usecase/ICreateMemberUseCase.java
src/main/java/com/alkemy/ong/domain/Member.java
src/main/java/com/alkemy/ong/infrastructure/config/spring/ServiceBeanConfig.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/MemberEntityMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/MemberRepository.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/MemberMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/mapper/SocialMediaMapper.java
src/main/java/com/alkemy/ong/infrastructure/rest/request/MemberRequest.java
src/main/java/com/alkemy/ong/infrastructure/rest/resource/MemberResource.java
src/main/java/com/alkemy/ong/infrastructure/rest/response/MemberResponse.java

- endpoint create new member /members
* ...
* ...
* ....

PR OT231-69: endpoint create member

---

src/main/java/com/alkemy/ong/infrastructure/database/repository/spring/IActivitySpringRepository.java
src/test/java/com/alkemy/ong/bigtest/BigTest.java
src/test/java/com/alkemy/ong/bigtest/activities/CreateActivityIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/activities/UpdateActivityIntegrationTest.java

* UpdateActivityIntegrationTest
* CreateActivityIntegrationTest

OT23-94 Test Activities
